#!/bin/bash
#PBS -q shortCPUQ
#PBS -N strong
#PBS -l select=2:ncpus=72:mpiprocs=72
#PBS -l walltime=00:30:00
#PBS -j oe
#PBS -o logs/strong.out

set -euo pipefail
cd "$PBS_O_WORKDIR"

module purge
module load gcc91
module load openmpi-3.0.0--gcc-9.1.0
module load cmake-3.15.4

mkdir -p logs results
chmod +x script/strong.sh

#real matrix
MATRIX="${MATRIX:-kron_g500-logn21.mtx}"

./script/strong.sh "$MATRIX" 1 static 64 10 5