#!/bin/bash
#PBS -q short_cpuQ
#PBS -N weak
#PBS -l select=2:ncpus=72:mpiprocs=72
#PBS -l walltime=00:30:00
#PBS -j oe
#PBS -o logs/weak.out

set -euo pipefail

cd "$PBS_O_WORKDIR"

module purge
module load gcc91
module load openmpi-3.0.0--gcc-9.1.0
module load cmake-3.15.4

mkdir -p logs results
chmod +x script/weak.sh

# Parametri weak
export ROWS_PER_RANK=16384
export NNZ_PER_RANK=1000000

# Lancia (non serve REPO_ROOT qui)
./script/weak.sh 1 static 64 10 5 "$ROWS_PER_RANK" "$NNZ_PER_RANK"